name: Pipeline Local DevSecOps

on:
  push:
    branches:
      - main

jobs:
  local-pipeline:
    runs-on: self-hosted
    steps:

    #  Stage 1: Checkout do código
    - name: Checkout do repositório
      uses: actions/checkout@v3

    #  Stage 2: Build com Maven
    - name: Compilar projeto Java
      run: |
        mvn clean package
        echo "Build finalizado com sucesso!"

    #  Stage 3: Deploy em cluster local (Kind + Helm)
    - name: Deploy com Helm
      run: |
        helm upgrade --install meu-app ./helm-chart \
          --set image.repository=meu-app \
          --set image.tag=latest
        kubectl get pods
